name: Build and deploy Next.js app to Azure Web App
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: npm install
        run: npm ci
      
      # List files before making changes
      - name: List files before
        run: ls -la
          
      - name: Create server.js file explicitly
        run: |
          cat > server.js << 'EOF'
          // Add diagnostic logging
          console.log("Starting server.js");
          console.log("NODE_ENV:", process.env.NODE_ENV);
          console.log("PORT:", process.env.PORT);
          console.log("CWD:", process.cwd());
          
          try {
            const fs = await import('fs');
            console.log("Files in directory:", fs.readdirSync(".").join(", "));
          } catch (e) {
            console.log("Could not list files:", e.message);
          }

          import { createServer } from "http";
          import { parse } from "url";
          import next from "next";
          import { fileURLToPath } from "url";
          import { dirname } from "path";

          // Create equivalent of __dirname for ES modules
          const __filename = fileURLToPath(import.meta.url);
          const __dirname = dirname(__filename);

          // Create the Next.js app
          const app = next({
            dev: process.env.NODE_ENV !== "production",
            dir: __dirname,
          });
          const handle = app.getRequestHandler();

          // Get port from environment variable
          const port = process.env.PORT || 3000;

          console.log("Initializing Next.js app...");
          // Prepare the app and start the server
          app
            .prepare()
            .then(() => {
              console.log("Next.js app prepared, starting HTTP server...");
              createServer((req, res) => {
                // Parse the URL
                const parsedUrl = parse(req.url, true);

                // Let Next.js handle the request
                handle(req, res, parsedUrl);
              }).listen(port, (err) => {
                if (err) throw err;
                console.log(`> Ready on http://localhost:${port}`);
                console.log(`> Environment: ${process.env.NODE_ENV}`);
              });
            })
            .catch((err) => {
              console.error("Error starting server:", err);
              console.error("Error details:", err.stack);
              process.exit(1);
            });
          EOF
          
          # Verify the file was created
          ls -la server.js
          cat server.js | head -10
      
      - name: Create next.config.mjs
        run: |
          echo "/** @type {import('next').NextConfig} */" > next.config.mjs
          echo "const nextConfig = {" >> next.config.mjs
          echo "  output: \"standalone\"," >> next.config.mjs
          echo "};" >> next.config.mjs
          echo "export default nextConfig;" >> next.config.mjs
          
      - name: Create optimized production build
        run: npm run build
      
      # List files to verify our deployment package contents
      - name: List files after build
        run: |
          echo "Root directory:"
          ls -la
          echo ""
          echo ".next directory:"
          ls -la .next
          
      - name: Zip artifact for deployment
        run: |
          # Make sure to include server.js explicitly
          zip -r release.zip . -x "*.git*" "node_modules/*" ".next/cache/*"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      # List files to verify server.js exists
      - name: List deployment files
        run: |
          echo "Contents of deployment package:"
          ls -la
          echo "Is server.js present?"
          if [ -f server.js ]; then
            echo "YES - server.js exists"
            cat server.js | head -5
          else
            echo "NO - server.js is missing"
          fi
        
      - name: Install production dependencies
        run: npm ci --omit=dev
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
