name: Build and deploy Node.js app to Azure Web App - app-advanced3-6
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: npm install and build
        run: |
          npm install
          npm run build
          
      - name: Create server.js
        run: |
          echo 'const { createServer } = require("http");
          const { parse } = require("url");
          const next = require("next");
          
          const app = next({ dev: false });
          const handle = app.getRequestHandler();
          const port = process.env.PORT || 3000;
          
          app.prepare().then(() => {
            createServer((req, res) => {
              const parsedUrl = parse(req.url, true);
              handle(req, res, parsedUrl);
            }).listen(port, () => {
              console.log(`> Ready on port ${port}`);
            });
          });' > server.js
          
      - name: Update package.json
        run: |
          sed -i 's/"scripts": {/"scripts": {\n    "postinstall": "next build",/g' package.json
          
      - name: Zip artifact for deployment
        run: |
          npm ci --production
          zip -r release.zip . -x "*.git*" "node_modules/[email protected]*" "node_modules/@[email protected]*"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
