name: Build and deploy Next.js app to Azure Web App
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: npm install
        run: npm ci
      
      - name: Create JavaScript config files
        run: |
          # Create next.config.js from next.config.ts
          echo "/** @type {import('next').NextConfig} */" > next.config.js
          echo "module.exports = {" >> next.config.js
          echo "  output: \"standalone\"," >> next.config.js
          echo "};" >> next.config.js
          
          # Create postcss.config.js
          echo "/** @type {import('postcss-load-config').Config} */" > postcss.config.js
          echo "module.exports = {" >> postcss.config.js
          echo "  plugins: {" >> postcss.config.js
          echo "    tailwindcss: {}," >> postcss.config.js
          echo "    autoprefixer: {}," >> postcss.config.js
          echo "  }," >> postcss.config.js
          echo "};" >> postcss.config.js
      
      - name: Create optimized production build
        run: npm run build
          
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*" ".next/cache/*"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Install production dependencies
        run: npm ci --omit=dev
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
