name: Build and deploy Next.js app to Azure Web App
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: npm install
        run: npm ci
      
      - name: Update package.json for ESM
        run: |
          # Add type:module to package.json
          jq '. + {"type":"module"}' package.json > temp.json && mv temp.json package.json
      
      - name: Create JavaScript config files
        run: |
          # Create next.config.mjs (ESM version)
          echo "/** @type {import('next').NextConfig} */" > next.config.mjs
          echo "const nextConfig = {" >> next.config.mjs
          echo "  output: \"standalone\"," >> next.config.mjs
          echo "};" >> next.config.mjs
          echo "export default nextConfig;" >> next.config.mjs
          
          # Create postcss.config.mjs (ESM version)
          echo "/** @type {import('postcss-load-config').Config} */" > postcss.config.mjs
          echo "export default {" >> postcss.config.mjs
          echo "  plugins: {" >> postcss.config.mjs
          echo "    tailwindcss: {}," >> postcss.config.mjs
          echo "    autoprefixer: {}," >> postcss.config.mjs
          echo "  }," >> postcss.config.mjs
          echo "};" >> postcss.config.mjs
      
      - name: Create optimized production build
        run: npm run build
          
      - name: Prepare for deployment
        run: |
          # Create a diagnostic file to verify imports are working
          echo "// Import path check" > check-imports.js
          echo "import { fileURLToPath } from 'url';" >> check-imports.js
          echo "import { dirname } from 'path';" >> check-imports.js
          echo "import fs from 'fs';" >> check-imports.js
          echo "" >> check-imports.js
          echo "// Print working directory and files" >> check-imports.js
          echo "console.log('CWD:', process.cwd());" >> check-imports.js
          echo "console.log('Files:', fs.readdirSync('.'));" >> check-imports.js
          echo "console.log('NODE_ENV:', process.env.NODE_ENV);" >> check-imports.js
          echo "console.log('PORT:', process.env.PORT);" >> check-imports.js
          echo "" >> check-imports.js
          echo "// Import server" >> check-imports.js
          echo "import './server.js';" >> check-imports.js
      
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*" ".next/cache/*"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Install production dependencies
        run: npm ci --omit=dev
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
